language: node_js
node_js:
  - lts/*
env:
  - EXTENSION_ID=mokknliiomknodkdmpcellamkopbdmao
script:
  - npm run lint
  - npm run test
  - npm run build
deploy:
  - provider: script
    skip_cleanup: true
    script: npm run release
    on:
      tags: true
